### ISSUE TITLE
Can we encode a document from command line?

### ISSUE THREAD

**Issue by dataislife** [getalp/Flaubert#12]
Hi, 

Is it possible to have a bash file that is doing the sentence encoding of each line of a given document in an optimised manner? 

Hence, if we compute something like the following: 
```
bash encode_doc.sh $DATA_PATH/doc.txt 
```
We could get sentence embeddings for each line of the document from $DATA_PATH/doc.txt. 
The assumption is that each line of our document correspond to a given sentence. 

Cheers and Good job! :D

**Comment by schwabdidier** [comment]
@dataislife maybe you can ask your question or have a look  in the transformer GitHub ?
