### ISSUE TITLE
Pre-training data for FlauBERT

### ISSUE THREAD

**Issue by manueltonneau** [getalp/Flaubert#14]
Hi all and thanks for open-sourcing Flaubert :) 

I'm going through the README, trying to find out on which dataset FlauBERT was trained on but I'm not able to find the information. There's a mention of Gutenberg data in the pre-processing example: is that the data you used?

Thanks a lot in advance!

**Comment by schwabdidier** [comment]
Hello, thank you for your comment. All information are provided in the arXiv article https://arxiv.org/abs/1912.05372

**Comment by manueltonneau** [comment]
Merci beaucoup :)
