### ISSUE TITLE
Convert from xlm to Hugging Face

### ISSUE THREAD

**Issue by king-menin** [getalp/Flaubert#19]
Hi, i trained my own BERT with your code.
Do you provide code for converting xlm model to Hugging Face model: from checkpoint.pth to pytorch_model.bin and config.json? also class for tokenizer?
Thank you!

**Comment by formiel** [comment]
Hi, 

Thank you for your question! We've just added the code to convert a pre-trained model to Hugging Face. Please refer to the instruction [here](https://github.com/getalp/Flaubert#33-convert-an-xlm-pre-trained-model-to-hugging-faces-transformers).
