### ISSUE TITLE
Enronsent usage

### ISSUE THREAD

**Issue by JbRemy** [getalp/Flaubert#23]
Hi, 

I am trying to reproduce the dataset you used for FlauBERT.
How did you use Enronsent which seams to be in English ?

Thank you in advance.

**Comment by formiel** [comment]
Hi @JbRemy , 

I've already answered you by email, but let me give an explanation here in case somebody needs in the future. Enronsent is originally in English. It was translated in a previous project of our team using phrase-based machine translation.

Please note that this corpus is rather small compared to the rest so I think it won't have any measurable impact on the results.
