### ISSUE TITLE
Datasets: EnronSent, Le Monde, PCT 

### ISSUE THREAD

**Issue by jchwenger** [getalp/Flaubert#25]
Hi,

First of all, thanks a lot for this set of tools, a boon for French language modelling!

Reading your paper, I've been wondering about some dataset choices:
- the EnronSent seems to be only in English, why did you include it? 
- I guess it's probably a no no, but is there any chance the two datasets from *Le Monde* and PCT might be released in some form or other? 

Thanks in advance!

**Comment by schwabdidier** [comment]
For EnronSent, please see issue #23 

For PCT, you can certainly find more info here (it is "free of charge for academic and private research institutions for re- search purposes only") https://www.researchgate.net/publication/303647463_COPPA_V20_Corpus_Of_Parallel_Patent_Applications_Building_Large_Parallel_Corpora_with_GNU_Make 

Le Monde is distributed by ELRA/ELDA

**Comment by jchwenger** [comment]
That clarifies it all, many thanks for your reply!
