### ISSUE TITLE
Model names

### ISSUE THREAD

**Issue by Khasir** [getalp/Flaubert#26]
The example in the readme for running with the Hugging Face library reads:
```
# Choose among ['flaubert-small-cased', 'flaubert-base-uncased', 'flaubert-base-cased', 'flaubert-large-cased']
modelname = 'flaubert-base-cased' 
```
but these don't work for me. Instead, what worked was:
```
# Choose among ['flaubert/flaubert_small_cased', 'flaubert/flaubert_base_uncased', 'flaubert/flaubert_base_cased', 'flaubert/flaubert_large_cased']
modelname = 'flaubert/flaubert_base_cased'
```

**Comment by formiel** [comment]
Thanks @Khasir for raising this issue! 

Indeed, since `transformers` 2.11.0, one has to use the full path to models. I have just updated the README to highlight the changes.
