### ISSUE TITLE
fastBPE

### ISSUE THREAD

**Issue by Mehdi07** [getalp/Flaubert#27]
Hello, 

Is it normal that the fastBPE folder is empty? That's why I got an error in prepare-data-pawsx.sh.

**Comment by formiel** [comment]
Hi @Mehdi07,

You should install fastBPE in the `./tools` directory as instructed in the [README](https://github.com/getalp/Flaubert#install-dependencies). Please let me know if it works for you.

**Comment by Mehdi07** [comment]
Hello, 

I installed fastBPE and everything is working fine, I am fine-tuning the model on XLM data.

But now I'd like to specialize Flaubert on my dataset. I have about 1000 lines, how can I do it?

Should I open a new issue to talk about this?

**Comment by Mehdi07** [comment]
Hello, 

I installed fastBPE and everything is working fine, I am fine-tuning the model on XLM data. Thank you!
