### ISSUE TITLE
model on official  transformers model repository

### ISSUE THREAD

**Issue by cedspam** [getalp/Flaubert#3]
it would be a good thing to have this pretrained model on the official model  repository of transformers

**Comment by formiel** [comment]
Thanks for your suggestion. We are currently working on it. Hopefully we’ll be able to create a pull request in a few days.

**Comment by cedspam** [comment]
no need for a pull request in fact just do 

```
wget https://zenodo.org/record/3567594/files/xlm_bert_fra_base_lower.tar
tar xf xlm_bert_fra_base_lower.tar
transformers-cli login
transformers-cli upload  xlm_bert_fra_base_lower
```
https://huggingface.co/transformers/model_sharing.html
it would be better to have your own official login

**Comment by formiel** [comment]
@cedspam Thank you very much for pointing that out! We have been working on integrating Flaubert natively into Hugging Face's `transformers`. The pretrained models (note the **s** ;) ) will be hosted on their official repo as well. Please stay tuned!

**Comment by formiel** [comment]
@cedspam We have integrated Flaubert into Hugging Face's `transformers`. Please see this [example of usage](https://github.com/getalp/Flaubert#11-using-flaubert-with-hugging-faces-transformers).
