### ISSUE TITLE
Pre-training FlauBERT with Google Colab?

### ISSUE THREAD

**Issue by mcriggs** [getalp/Flaubert#39]
Would it be possible to pre-train Flaubert (as described here https://github.com/getalp/Flaubert#3-pre-training-flaubert) in Google Colab? If so, would you be able to give me some advice on converting the code you supply so that it works in Colab?

Thank you in advance for your time. :)

**Comment by schwabdidier** [comment]
definitely, it depends on corpus size. You will find exact values in the article but for 71 Go of text (see https://arxiv.org/pdf/1912.05372.pdf) :

FlauBERTBASE is trained on 32 GPUs Nvidia V100 in 410 hours ( = 546 days) and FlauBERTLARGE is trained on 128 GPUs in 390 hours (=2080 days). It is too huge for google collab

If it is a specialized corpus, consider starting from one Flaubert model and continue learning with your own corpus for instance as describe in this article (https://arxiv.org/pdf/1901.08746.pdf). Even in this case, I am not sure it will be possible as your corpus is certainly too big.

**Comment by mcriggs** [comment]
@schwabdidier Thank you for your prompt response!

I should have been more specific when I posed my question. I want to do further training on the flaubert-large-cased model with a corpus of lemmatized eighteenth-century French text. (I corresponded a bit with @TCMVince and @formiel about this already.) I don't yet know the exact size of this corpus. (The corpus will include the eighteenth-century French texts from Wikisource and Gutenberg).

Given that I'm going to do further training on an existing FlauBERT model and that my corpus will be relatively small, could you give me some sense of the computer resources that I will need to carry out the training. I ask simply because I doubt I have the necessary resources myself and will need to find a lab where I can do the training.

Thank you in advance for your help!
