### ISSUE TITLE
Example de paraphrase

### ISSUE THREAD

**Issue by ExtReMLapin** [getalp/Flaubert#44]
Bonjour,
Dans la documentation de Flaubert, il est fait mention de la possibilité de paraphraser.
Auriez-vous un exemple de code à utiliser pour, par exemple, d'une phrase en générer une dizaines de similaires ?

Merci

**Comment by formiel** [comment]
Hello @ExtReMLapin !

I'm sorry for my very late response! The [paraphrasing task in FLUE ](https://github.com/getalp/Flaubert/tree/master/flue#2-paraphrasing-paws-x)(French Language Understanding Evaluation benchmark that we proposed together with FlauBERT) is a paraphrase identification task in which the model learns to distinguish whether a given pair of sentences are semantically equivalent or not. FlauBERT is pre-trained with MLM only and thus it's not suited for text generation. To do paraphrasing, I would suggest fine-tuning a pre-trained sequence-to-sequence model such as BART on a paraphrasing dataset.
