### ISSUE TITLE
1.get_toolkit.sh 

### ISSUE THREAD

**Issue by jourlin** [getalp/Flaubert#5]
The script failed with :
**No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?**
I managed to fix it with : 
`sudo update-alternatives --config java`
and selecting `/usr/lib/jvm/java-11-openjdk-amd64/bin/java` as default

**Comment by formiel** [comment]
@jourlin Thank you very much for reporting that issue!
@coylz Do you think we should add this to the documentation?

**Comment by loic-vial** [comment]
Hi, 
Yes, I will provide more information in the Readme about this :)

**Comment by schwabdidier** [comment]
My opinion : if someone wonder something, we can consider that someone else will wonder the same and then we can add it to the documentation. Thank you @jourlin

**Comment by schwabdidier** [comment]
Is it done @coylz ? If yes, please close the issue. If no, you know what to do before you close the issue :)

**Comment by loic-vial** [comment]
I added a little more info on the Readme (Java JDK needed)
