### ISSUE TITLE
*Error in `python3': free(): invalid pointer: 0x000055ae110d8c20 *****  Abandon

### ISSUE THREAD

**Issue by keloemma** [getalp/Flaubert#8]
Hello,

I am using Flaubert with huggingface transformers but I am getting negative vectors I do not know why ? 

Do you have any idea why ? when using your previous  installation without it the vectors were non negatives.

tensor([[[-0.7107, -1.4737,  0.9828,  ..., -3.1127,  0.3499,  0.3747],
         [-1.7784, -2.2899, -0.3564,  ..., -0.7091, -0.7323,  2.5189],
         [-1.3886, -0.6179, -1.2058,  ..., -0.5359, -0.5513,  0.4187],
         ...,
         [ 1.0148, -2.3575, -0.9193,  ..., -2.2937,  0.5353,  0.6768],
         [ 0.9082, -2.2049, -1.2324,  ..., -2.1818,  0.5374,  0.8427],
         [ 0.9287, -1.7471, -1.7460,  ..., -2.1425,  0.5514,  0.7766]],

        [[-0.9680, -1.0419,  0.6869,  ..., -2.0340,  0.5130, -0.0712],
         [-0.9206, -1.6208, -0.1860,  ...,  0.6649, -1.0081, -0.8190],
         [-1.1192, -1.6612, -0.2082,  ..., -0.2693, -1.8960, -0.6337],
         ...,
         [ 0.1435, -2.2177, -0.5040,  ..., -1.8233,  0.8659,  0.0530],
         [ 0.0633, -2.1492, -0.5994,  ..., -1.7436,  0.7928,  0.1566],
         [ 0.0480, -1.8401, -0.7709,  ..., -1.6504,  0.7304,  0.0832]],

        [[-0.5683, -2.7551,  1.0667,  ..., -3.7187,  1.6681,  0.8379],
         [-2.0996, -0.8701, -1.2148,  ..., -0.0379, -2.5241,  1.9351],
         [-3.7073,  0.3279,  0.8807,  ..., -1.3985, -2.0611,  0.6002],
         ...,
         [ 1.3348, -3.6816, -1.0271,  ..., -1.6550,  0.8394,  1.0457],
         [ 0.8955, -3.6031, -1.0443,  ..., -1.2973,  0.9316,  1.3558],
         [ 1.0691, -3.5659, -1.1623,  ..., -1.3626,  1.1174,  1.3523]],

        ...,

        [[-0.9926, -1.0781,  0.5332,  ..., -1.9912,  0.3508, -0.1276],
         [-0.9452,  1.4486, -0.4952,  ..., -0.2910,  0.1014,  0.7436],
         [-2.1879, -0.1735,  1.2844,  ..., -1.4701, -0.3949, -1.3691],
         ...,
         [-0.0380, -1.8997, -0.2480,  ..., -1.6570,  0.9166,  0.3879],
         [-0.0185, -1.7595, -0.4073,  ..., -1.6960,  0.7043,  0.4340],
         [ 0.0889, -1.6022, -0.6427,  ..., -1.7312,  0.6539,  0.3327]],

        [[-0.7026, -2.8673,  0.7728,  ..., -3.2812,  1.2357,  1.0315],
         [-0.7316,  1.7105, -0.2076,  ...,  0.0276,  0.4884,  0.5200],
         [-2.2086, -0.0808,  1.7520,  ..., -0.2885,  0.3539, -0.3582],
         ...,
         [ 1.2960, -4.0501, -1.3244,  ..., -1.6143,  0.6550,  1.8709],
         [ 0.9846, -3.8275, -1.3272,  ..., -1.1076,  0.6045,  1.9635],
         [ 1.0963, -3.6684, -1.3650,  ..., -1.1385,  0.6555,  1.7605]],

        [[-0.8365, -2.3553,  0.7874,  ..., -3.7243,  1.6223,  0.8726],
         [-0.2939, -2.7249,  0.2032,  ..., -2.4267, -1.7648,  1.4637],
         [ 0.1375,  0.9276,  0.0405,  ..., -0.4353, -1.1491,  1.0354],
         ...,
         [ 1.6176, -3.3541, -1.4429,  ..., -2.5446,  0.8072,  1.7173],
         [ 1.2283, -3.1744, -1.2734,  ..., -2.0969,  0.7972,  1.9605],
         [ 1.4354, -2.9385, -1.1689,  ..., -2.0097,  1.0124,  1.8885]]],
       grad_fn=<MulBackward0>)
torch.Size([260, 324, 768])
--fin--

My code : 

def Flaubert_Model(texte): # texte is a column of sentences
    
    # You could choose among ['flaubert-base-cased', 'flaubert-base-uncased', 'flaubert-large-cased']
    modelname = 'flaubert-base-cased' 

    flaubert, log = FlaubertModel.from_pretrained(modelname, output_loading_info=True)

    flaubert_tokenizer = FlaubertTokenizer.from_pretrained(modelname, do_lowercase=False) # do_lowercase=False if using the 'cased' model, otherwise it should be set to False

    tokenized = texte.apply((lambda x: flaubert_tokenizer.encode(x, add_special_tokens=True)))

    max_len = 0
    for i in tokenized.values:
        if len(i) > max_len:
            max_len = len(i)

    padded = np.array([i + [0] * (max_len - len(i)) for i in tokenized.values])

    print(padded)

    # Using model

    token_ids = torch.tensor(padded)

    last_layer =  flaubert(token_ids)[0]

    print(last_layer)
    print(last_layer.shape)

**Comment by schwabdidier** [comment]
@keloemma Is it a problem to have negative components ? I don't understand the relation between the title (Error in `python3') and the question.

**Comment by keloemma** [comment]
@schwabdidier  Sorry, I badly write the problem I was encountering, seems the error :  *Error in `python3': free(): invalid pointer: 0x000055ae110d8c20 ***** Abandon #8 was linked to the type of server I was runnning the script. I moved to anther one and run the script and the error desappeared.
